POST http://localhost:3001/api/cards/select
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.T2xpdmVyTQ.4fIWE_1q69-3Aptytr0pdqNS8vVD1cCksoUw0hR0TWU

{
    "username": "OliverM",
    "cardIndex": 3
}